# site properties and page defaults
title: Visual Cognition Lab
# subtitle: 
description: vision, facial recognition, attention, decision-making, modeling
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: visualcognitionlab.ln@gmail.com
  orcid: 0000-0002-7248-0301
  google-scholar: MyN21LIAAAAJ&hl=en
  github: vcl-ln
  # twitter: vcl-ln
  # youtube: vcl-ln

# site nav bar
nav:
  - link: research
    tooltip: Current research projects
  - link: publications
    tooltip: Published works
  - link: team
    tooltip: About our team
  - link: News
    tooltip: News and events
  - link: news
    tooltip: News and commentary
  - link: join
    tooltip: Join the lab
  - link: contact
    tooltip: Email, address, and location

# base directory where site is hosted
logo: 
header: images/background.png
footer: images/background.png
baseurl: /

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
